<?php
$activeTab = [
    'index' => true,
    'requests' => false,
    'dataset' => $dataset
];
?>
<?= $this->partial('mkdf/policies/partial/navtabs', $activeTab); ?>
<br />

<h5>Licenses in use</h5>

<table class="table table-bordered">
    <tr>
        <th>API Key</th>
        <th>License</th>
        <!-- <th>Actions</th> -->
    </tr>
<?php foreach ($licensesAssigned as $association): ?>
    <tr>
        <td><?= $association['key'] ?></td>
        <td><?= $association['license'] ?></td>
    </tr>
<?php endforeach; ?>

</table>
<small class="form-text text-muted">License/key allocation can be changed via the <em>API</em> tab. </small>
<hr />
<h5>Licenses available</h5>
<h6>Dataset</h6>
<table class="table table-bordered">
    <tr>
        <th>License title</th>
        <th>Actions</th>
    </tr>
<?php foreach ($licenses as $license): ?>
    <tr>
        <td><?= $license['schema:title']; ?></td>
        <td>
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#licenseViewModal" onclick="loadLicense('<?= $license['odrl:uid'] ?>', '<?= $dataset->uuid ?>', '<?= $license['schema:title'] ?>')">
                <i class="fas fa-search"></i> View
            </button>
        </td>
    </tr>

<?php endforeach; ?>
</table>

<h6>JSON documents</h6>
<table class="table table-bordered">
    <tr>
        <th>JSON doc ID</th>
        <th>License title</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($licensesJson as $license): ?>
        <tr>
            <td><?= $license['resourceID']; ?></td>
            <td><?= $license['schema:title']; ?></td>
            <td>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#licenseViewModal" onclick="loadLicense('<?= $license['odrl:uid'] ?>', '<?= $dataset->uuid ?>', '<?= $license['schema:title'] ?>')">
                    <i class="fas fa-search"></i> View
                </button>
            </td>
        </tr>

    <?php endforeach; ?>
</table>


<h6>Files</h6>
<table class="table table-bordered">
    <tr>
        <th>Filename</th>
        <th>License title</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($licensesFile as $license): ?>
        <tr>
            <td><?= $license['resourceID']; ?></td>
            <td><?= $license['schema:title']; ?></td>
            <td>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#licenseViewModal" onclick="loadLicense('<?= $license['odrl:uid'] ?>', '<?= $dataset->uuid ?>', '<?= $license['schema:title'] ?>')">
                    <i class="fas fa-search"></i> View
                </button>
            </td>
        </tr>

    <?php endforeach; ?>
</table>

<script>
    function loadLicense(licenseID, datasetUUID, title) {
        $("#permissionList").empty();
        $("#obligationList").empty();
        $("#prohibitionList").empty();
        // Check if it's a standard library license or a dataset-specific custom license...
        var custom = false;
        var url;
        //echo();
        if (licenseID.substring(0,8) == "-custom-") {
            custom = true;
            licenseName = licenseID.substring(8);
            url = "/dataset/policies/custom/" + datasetId + "?license=" + licenseName;
        }
        else {
            licenseName = licenseID;
            url = "/policies/" + licenseName;
        }

        document.getElementById("licenseViewModalContent").innerHTML = "LOADING: " + title + "...";
        $.getJSON(url, function(result){
            console.log(result);
            //document.getElementById("licenseViewModalContent").innerHTML = JSON.stringify(result[0], null, 2);
            document.getElementById("licenseViewModalContent").innerHTML = '<h6>' + title + '</h6><hr />';
            renderPermissions(result[0]['odrl:permission']);
            renderObligations(result[0]['odrl:obligation']);
            renderProhibitions(result[0]['odrl:prohibition']);
            //console.log
        });
    }

    function loadPermissionModalContent(index) {

    }

    function renderPermissions(permissions) {
        //console.log(permissions);
        $("#permissionList").empty();
        if (Array.isArray(permissions)) {
            modalText = '';
            for (i = 0; i < permissions.length; i++) {
                liText = "<li class='list-group-item'> <span class='text-success'> <i class='fas fa-check-circle'></i></span>";
                liText += " " + getShortName(permissions[i].action[0]) + " ";
                if (i > 0) {
                    modalText += "<hr />";
                }
                modalText += "<h6>" + permissions[i].action[0] + "</h6>";
                modalText += "<p><em>permission description</em></p>";

                if (Array.isArray(permissions[i].duty)) {
                    liText += "<a href='#' class='text-warning' data-toggle='tooltip' data-placement='top' title='One or more duties are attached to this permission policy'>";
                    liText += "<i class='fas fa-exclamation-circle'></i></a>";
                    modalText += "<p> <span class='text-danger'><i class='fas fa-exclamation-circle'></i></span> The following duties are attached to this permission:<br />";
                    for (j = 0; j < permissions[i].duty.length; j++) {
                        modalText += "<em>" + permissions[i].duty[j] + "</em><br />";
                    }
                    modalText += "</p>";

                }
                $("#permissionList").append(liText);
                $("#permissionModalContent").html(modalText);
            }
        }
    }

    function renderObligations(obligations) {
        $("#obligationList").empty();
        if (Array.isArray(obligations)) {
            modalText = '';
            for (i = 0; i < obligations.length; i++) {
                liText = "<li class='list-group-item'> <span class='text-info'> <i class='fas fa-exclamation-circle'></i></span>";
                liText += " " + getShortName(obligations[i].action[0]) + " ";
                if (i > 0) {
                    modalText += "<hr />";
                }
                modalText += "<h6>" + obligations[i].action[0] + "</h6>";
                modalText += "<p><em>obligation description</em></p>";
                $("#obligationList").append(liText);
                $("#obligationModalContent").html(modalText);

            }
        }
    }

    function renderProhibitions(prohibitions) {
        $("#prohibitionList").empty();
        if (Array.isArray(prohibitions)) {
            modalText = '';
            for (i = 0; i < prohibitions.length; i++) {
                liText = "<li class='list-group-item'> <span class='text-danger'> <i class='fas fa-times-circle'></i></span>";
                liText += " " + getShortName(prohibitions[i].action[0]) + " ";
                if (i > 0) {
                    modalText += "<hr />";
                }
                modalText += "<h6>" + prohibitions[i].action[0] + "</h6>";
                modalText += "<p><em>prohibition description</em></p>";
                $("#prohibitionList").append(liText);
                $("#prohibitionModalContent").html(modalText);
            }
        }
    }

    function getShortName(input) {
        position = input.lastIndexOf('#');
        if (position < 0){
            position = input.lastIndexOf(':');
        }
        if (position < 0) {
            return input;
        }
        else {
            return input.substring(position + 1);
        }
    }

    $(document).ready(function(){
        //loadLicense();
    });
</script>

