<h1>Apply license</h1>
<?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>
<!-- Token: <?= $token ?> -->
<p>
    Are you sure you wish to apply this license to the dataset?<br />
    <em>license name</em><br />
</p>
<?= $this->partial('mkdf/core/partial/actions', [
    'buttons'=>[
        ['type'=>'primary','label'=>'Yes, apply this license', 'target'=> 'dataset-policies', 'params'=> ['id' => $dataset->id, 'action' => 'apply'], 'query' => ['license' => $license, 'token' => $token]],
        ['type'=>'danger','label'=>'No, go back please', 'target'=> 'dataset-policies', 'params'=> ['id' => $dataset->id, 'action' => 'index']]]
] ); ?>
