<h1><?= $dataset->title ?></h1>
<div class="container">

    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>

            <h2>Licenses and policies</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->
            <br /><br />

            <div class="row">
                <div class="col-md-12">
                    <?php
                    $heading = "Make a license counter offer";
                    $titleLabel = "Counter offer license title";
                    $descriptionLabel = "Counter offer license description";
                    $submitLabel = "Make counter offer";
                    $returnURL = $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'requests'],[]);

                    $policybuilderParams = [
                        'formSubmitUrl' =>  $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'counter'],['query' => ['request' => $request]]),
                        'allPolicies' => $allPolicies,
                        'heading' => $heading,
                        'titleLabel' => $titleLabel,
                        'descriptionLabel' => $descriptionLabel,
                        'submitLabel' => $submitLabel,
                        'returnURL' => $returnURL,
                    ];
                    ?>


                    <?= $this->partial('mkdf/policies/partial/policybuilder', $policybuilderParams); ?>



                    <hr />
                    <h4>Previous request details</h4>
                    <p>
                        <strong>User: </strong><?= $requestObj['user'] ?><br />
                        <strong>Date: </strong><?= date('Y/m/d H:i',$mostRecentRequest['timestamp']) ?><br />
                        <strong>Request: </strong><?= $mostRecentRequest['title'] ?><br />
                        <strong>Description: </strong><?= $mostRecentRequest['description'] ?><br />




                        <?= $this->partial('mkdf/policies/partial/licenseview', ['policies' => $mostRecentRequest['policies']] ) ?>

                </div>
            </div>
        </div>
    </div>

</div>
