<h1>Create new license</h1>
<?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>
<!-- Token: <?= $token ?> -->
<p>
    Are you sure you wish to create this custom license?<br />
    <em>Please note that this will be added to your list of custom licenses but not automatically applied to the dataset until specifically selected</em>
    <em>license name</em><br />
</p>
<?= $this->partial('mkdf/core/partial/actions', [
    'buttons'=>[
        ['type'=>'primary','label'=>'Yes, create this license', 'target'=> 'dataset-policies', 'params'=> ['id' => $dataset->id, 'action' => 'createconfirm'], 'query' => ['license' => $license, 'userScope' => $userScope, 'assigneeEmail' => $assigneeEmail, 'token' => $token]],
        ['type'=>'danger','label'=>'No, go back please', 'target'=> 'dataset-policies', 'params'=> ['id' => $dataset->id, 'action' => 'index']]]
] ); ?>

<?php
    var_dump($policies);
?>
