
    <h1>Custom license created</h1>
    <?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>


<div class="row">
    <div class="col-md-12">

    License title: <em><?= $newLicense['schema:title'] ?></em><br />
    <p>
        This license will now be available to select from the list of available licenses for this dataset. Please note
        that the license has not yet been applied, so should be selected and applied in the normal way.
    </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <!-- <button id="saveButton" class="btn btn-primary align-baseline"></button> -->
        <a class="btn btn-primary" href="<?= $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'index'],[]); ?>" role="button">
            <i class="fas fa-redo"></i> Return to dataset licenses and polices
        </a>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h4>License source:</h4>
    </div>
</div>
<div class="row">
    <div class="col-md-12">

    <?php
    print("<pre>");
    print(json_encode($newLicense,JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    print("</pre>");
?>
    </div>
</div>
