<h1><?= $dataset->title ?></h1>
<div class="container">

    <!-- Modals -->
    <div class="modal fade" id="licenseScopeModal" tabindex="-1" aria-labelledby="licenseScopeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="selectScope" method="get" action="<?= $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'index'],[]); ?>">
                <div class="modal-header">
                    <h5 class="modal-title" id="licenseScopeModalLabel">Change License Scope</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span id="licenseScopeModalContent">
                    <?php
                    $licenseScopeOptions = ['dataset', 'jsondoc', 'file']
                    ?>
                    <select class="form-control" id="licensescope" name="licensescope">
                        <?php foreach($licenseScopeOptions as $licenseScopeItem): ?>
                            <?php $selected = ($licenseScopeItem == $licenseScope ? "selected" : ""); ?>
                            <option value='<?= $licenseScopeItem ?>' <?= $selected ?>><?= $licenseScopeItem ?></option>
                        <?php endforeach; ?>
                    </select>
                        <em>Note: License assignee and  target resource selection will be cleared</em>
                    </span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Reload</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <!-- ******************* -->
    <div class="modal fade" id="assigneeModal" tabindex="-1" aria-labelledby="assigneeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="selectAssignee" method="get" action="<?= $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'index'],[]); ?>">
                    <input type="hidden" name="licensescope" id="licensescope" value="<?= $licenseScope ?>">
                <div class="modal-header">
                    <h5 class="modal-title" id="assigneeModalLabel">Change License Assignee</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span id="assigneeModalContent">
                    <select class="form-control" id="assignee" name="assignee">
                        <?php foreach($assigneeList as $assigneeListItem): ?>
                            <?php $selected = ($assigneeListItem == $assignee ? "selected" : ""); ?>
                            <option value='<?= $assigneeListItem ?>' <?= $selected ?>><?= $assigneeListItem ?></option>
                        <?php endforeach; ?>
                    </select>
                        <em>Note: License target resource selection will be cleared</em>
                    </span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Reload</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <!-- ******************* -->
    <div class="modal fade" id="resourceModal" tabindex="-1" aria-labelledby="resourceModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="selectResource" method="get" action="<?= $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'index'],[]); ?>">
                    <input type="hidden" name="licensescope" id="licensescope" value="<?= $licenseScope ?>">
                    <input type="hidden" name="assignee" id="assignee" value="<?= $assignee ?>">

                    <div class="modal-header">
                    <h5 class="modal-title" id="resourceModalLabel">Change License target resource</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span id="resourceModalContent">
                    <select class="form-control" id="resourceid" name="resourceid">
                        <?php

                        ?>
                        <?php foreach($resourceList as $resourceListItem): ?>
                            <?php $selected = ($resourceListItem == $resourceId ? "selected" : ""); ?>
                            <option value='<?= $resourceListItem ?>' <?= $selected ?>><?= $resourceListItem ?></option>
                        <?php endforeach; ?>
                    </select>
                    </span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Reload</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <!-- ******************* -->

    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>

            <h2>Licenses and policies</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->
            <br /><br />

            <?php
            $activeTab = [
                'index' => true,
                'requests' => false,
                'dataset' => $dataset
            ];
            ?>
            <?= $this->partial('mkdf/policies/partial/navtabs', $activeTab); ?>

            <br />

            <div class="row">
                <div class="col-md-12">
                    <h6>
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#licenseScopeModal">
                        <i class="fas fa-exchange-alt"></i> Change
                    </button>

                        &nbsp;&nbsp;License scope: <em><?= $licenseScope ?></em></h6>
                </div>

            </div>

            <div class="row">
                <div class="col-md-12">
                    <h6>
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#assigneeModal">
                        <i class="fas fa-exchange-alt"></i> Change
                    </button>
                        &nbsp;&nbsp;License assignee: <em><?= $assignee ?></em></h6>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <h6>
                        <?php $disabled = ($licenseScope == 'dataset' ? "disabled" : ""); ?>
                        <?php $buttonClass = ($licenseScope == 'dataset' ? "btn-secondary" : "btn-primary"); ?>
                    <button type="button" class="btn <?= $buttonClass ?> btn-sm" data-toggle="modal" data-target="#resourceModal" <?= $disabled ?>>
                        <i class="fas fa-exchange-alt"></i> Change
                    </button>

                    &nbsp;&nbsp;License target resource: <em><?= $resourceId ?></em></h6>
                </div>
            </div>




            <hr />

            <h5><?= $license['schema:title'] ?></h5>

            <div class="accordion" id="accordionExample">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                License details and actions
                            </button>
                        </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            <p>
                                <strong>License: </strong><?= $license['schema:title'] ?><br />
                                <strong>License scope: </strong><em><?= $licenseScope ?></em><br />
                                <strong>Assignee scope: </strong><em><?= $assignee ?></em><br />
                                <strong>Target resource: </strong><em><?= $resourceId ?></em>
                            </p>
                            <!--
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a class="btn btn-danger" href="<?= $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'delete'],[]); ?>" role="button"><i class="fas fa-trash-alt"></i> Remove license</a>
                                <a class="btn btn-warning" href="#" role="button"><i class="fas fa-edit"></i> Modify license</a>
                            </div>
                            -->

                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingTwo">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                License policies
                            </button>
                        </h5>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                        <div class="card-body">
                            <!-- policies here -->
                            <div class="row">
                                <div class="col-md-4">
                                    <h5>Permissions
                                        <a href='#' class='text-secondary' data-toggle='modal' data-target='#permissionModal'><i class='fas fa-info-circle'></i></a>
                                    </h5>
                                    <ul class="list-group" id="permissionList">
                                        <?php
                                        foreach ($license['odrl:permission'] as $permission) {
                                            echo('<li class="list-group-item">');
                                            echo('<span class="text-success"><i class="fas fa-check-circle"></i> </span>');
                                            $pos = strrpos($permission['action'][0],'#');
                                            if (!$pos) {
                                                $pos = strrpos($permission['action'][0],':');
                                            }
                                            if (!$pos) {
                                                $shortname = $permission['action'][0];
                                            }
                                            else {
                                                $shortname = substr($permission['action'][0], $pos + 1);
                                            }
                                            echo($shortname);
                                            // TODO - add flag here if obligations attached
                                            echo('</li>');
                                        }
                                        ?>
                                    </ul>
                                </div>
                                <div class="col-md-4">
                                    <h5>Obligations
                                        <a href='#' class='text-secondary' data-toggle='modal' data-target='#obligationModal'><i class='fas fa-info-circle'></i></a>
                                    </h5>
                                    <ul class="list-group" id="obligationList">
                                        <?php
                                        foreach ($license['odrl:obligation'] as $obligation) {
                                            echo('<li class="list-group-item">');
                                            echo('<span class="text-info"><i class="fas fa-exclamation-circle"></i> </span>');
                                            $pos = strrpos($obligation['action'][0],'#');
                                            if (!$pos) {
                                                $pos = strrpos($obligation['action'][0],':');
                                            }
                                            if (!$pos) {
                                                $shortname = $obligation['action'][0];
                                            }
                                            else {
                                                $shortname = substr($obligation['action'][0], $pos + 1);
                                            }
                                            echo($shortname);
                                            echo('</li>');
                                        }
                                        ?>
                                    </ul>
                                </div>
                                <div class="col-md-4">
                                    <h5>Prohibitions
                                        <a href='#' class='text-secondary' data-toggle='modal' data-target='#prohibitionModal'><i class='fas fa-info-circle'></i></a>
                                    </h5>
                                    <ul class="list-group" id="prohibitionList">
                                        <?php
                                        foreach ($license['odrl:prohibition'] as $prohibition) {
                                            echo('<li class="list-group-item">');
                                            echo('<span class="text-danger"><i class="fas fa-times-circle"></i> </span>');
                                            $pos = strrpos($prohibition['action'][0],'#');
                                            if (!$pos) {
                                                $pos = strrpos($prohibition['action'][0],':');
                                            }
                                            if (!$pos) {
                                                $shortname = $prohibition['action'][0];
                                            }
                                            else {
                                                $shortname = substr($prohibition['action'][0], $pos + 1);
                                            }
                                            echo($shortname);
                                            echo('</li>');
                                        }
                                        ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingSource">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseSource" aria-expanded="false" aria-controls="collapseSource">
                                License ODRL source
                            </button>
                        </h5>
                    </div>
                    <div id="collapseSource" class="collapse" aria-labelledby="headingSource" data-parent="#accordionExample">
                        <div class="card-body">
                            <pre>
<?= stripslashes(json_encode($license, JSON_PRETTY_PRINT)) ?>
                            </pre>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingThree">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Dataset/resource target license history <em>(assignee: <?= $assignee ?>)</em>
                            </button>
                        </h5>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                        <div class="card-body">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">License</th>
                                    <th scope="col">Valid from</th>
                                    <th scope="col">Valid until</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($history as $row) {
                                    print ("<tr>");
                                    print ("<td>".$row['schema:title']."</td>");
                                    print ("<td>".date("d/m/Y H:i:s", $row['schema:validFrom'])."</td>");
                                    print ("<td>".date("d/m/Y H:i:s", $row['schema:validUntil'])."</td>");
                                    print ("</tr>");
                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>







        </div>
    </div>
</div>

