<h1><?= $dataset->title ?></h1>
<div class="container">


    <!-- *** MODAL - LICENSE VIEW *** -->
    <div class="modal fade bd-example-modal-lg" id="licenseViewModal" tabindex="-1" aria-labelledby="licenseViewModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="licenseViewModalLabel">License detail</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span id="licenseViewModalContent">
                        ...
                    </span>
                    <div class="row">
                        <div class="col-md-4">
                            <h6>Permissions
                                <a href='#' class='text-secondary' data-toggle='modal' data-target='#permissionModal'><i class='fas fa-info-circle'></i></a>
                            </h6>
                            <ul class="list-group" id="permissionList">
                                <li class="list-group-item">
                                    <span class="text-success"><i class="fas fa-check-circle"></i></span>
                                    Private use
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                                <li class="list-group-item">
                                    <span class="text-success"><i class="fas fa-check-circle"></i></span>
                                    Distribution
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                                <li class="list-group-item">
                                    <span class="text-success"><i class="fas fa-check-circle"></i></span>
                                    Modification
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h6>Obligations
                                <a href='#' class='text-secondary' data-toggle='modal' data-target='#obligationModal'><i class='fas fa-info-circle'></i></a>
                            </h6>
                            <ul class="list-group" id="obligationList">
                                <li class="list-group-item">
                                <span class="text-info">
                                    <i class="fas fa-exclamation-circle"></i></span>
                                    Attribution
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                                <li class="list-group-item"><span class="text-info">
                                    <i class="fas fa-exclamation-circle"></i></span>
                                    Liability
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h6>Prohibitions
                                <a href='#' class='text-secondary' data-toggle='modal' data-target='#prohibitionModal'><i class='fas fa-info-circle'></i></a>
                            </h6>
                            <ul class="list-group" id="prohibitionList">
                                <li class="list-group-item">
                                    <span class="text-danger"><i class="fas fa-times-circle"></i></span>
                                    Commercial use
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                                <li class="list-group-item">
                                    <span class="text-danger"><i class="fas fa-times-circle"></i></span>
                                    Modification
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- *** [END] MODAL - LICENSE VIEW *** -->


    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>

            <h2>Licenses and policies</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->
            <br /><br />

            <?php if($can_edit): ?>

            <?= $this->partial('mkdf/policies/partial/index-owner', [
                'messages' => $messages,
                'dataset' => $dataset,
                'actions' => $actions,
                'can_edit' => $can_edit,
                'can_read' => $can_read,
                'licenses' => $licenses,
                'history' => $history,
                'assigneeList' => $assigneeList,
                'assignee' => $assignee,
                'licenseScope' => $licenseScope,
                'resourceList' => $resourceList,
                'resourceId' => $resourceId,
                'licensesAssigned' => $licensesAssigned,
            ] )
            ?>
            <?php else: ?>

                <?= $this->partial('mkdf/policies/partial/index-user', [
                    'messages' => $messages,
                    'dataset' => $dataset,
                    'actions' => $actions,
                    'can_edit' => $can_edit,
                    'can_read' => $can_read,
                    'licenses' => $licenses,
                    'licensesJson' => $licensesJson,
                    'licensesFile' => $licensesFile,
                    'licensesAssigned' => $licensesAssigned
                ] )
                ?>

            <?php endif; ?>









        </div>
    </div>
</div>

