<h1><?= $dataset->title ?></h1>
<div class="container">

    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>

            <h2>Licenses and policies</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->
            <br /><br />

            <?php
            $activeTab = [
                'index' => false,
                'newrequest' => true,
                'requests' => false,
                'dataset' => $dataset
            ];
            ?>
            <?= $this->partial('mkdf/policies/partial/navtabs', $activeTab); ?>

            <br />

            <div class="row">
                <div class="col-md-12">
                    <?php
                    $heading = "Request a license";
                    $titleLabel = "Request reason: describe your request in a few words";
                    $descriptionLabel = "Please provide more detailed information about your request here if appropriate";
                    $submitLabel = "Submit request";
                    $returnURL = $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'requests'],[]);

                    $policybuilderParams = [
                        'formSubmitUrl' =>  $this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'newrequest'],[]),
                        'allPolicies' => $allPolicies,
                        'heading' => $heading,
                        'titleLabel' => $titleLabel,
                        'descriptionLabel' => $descriptionLabel,
                        'submitLabel' => $submitLabel,
                        'returnURL' => $returnURL,
                    ];
                    ?>


                    <?= $this->partial('mkdf/policies/partial/policybuilder', $policybuilderParams); ?>

                </div>
            </div>
        </div>
    </div>

</div>