<h1><?= $dataset->title ?></h1>
<div class="container">

    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>

            <h2>Licenses and policies</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->
            <br /><br />

            <?php
            $activeTab = [
                'index' => false,
                'requests' => true,
                'dataset' => $dataset
            ];
            ?>
            <?= $this->partial('mkdf/policies/partial/navtabs', $activeTab); ?>

            <br />

            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Requested</th>
                            <th scope="col">Modified</th>
                            <th scope="col">Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>text</td>
                            <td>text</td>
                            <td>REQUESTED</td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>text</td>
                            <td>text</td>
                            <td>REJECTED</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>text</td>
                            <td>text</td>
                            <td>APPROVED</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>