<h1><?= $dataset->title ?></h1>
<div class="container">


    <!-- *** MODAL - REQUEST HISTORY ITEM VIEW *** -->
    <div class="modal fade bd-example-modal-lg" id="historyItemModal" tabindex="-1" aria-labelledby="historyItemModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="historyItemModalLabel">License request details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span id="historyItemModalContent">
                        ...
                    </span>

                    <div class="row" id="policiesRow">
                        <div class="col-md-4">
                            <h6>Permissions
                                <a href='#' class='text-secondary' data-toggle='modal' data-target='#permissionModal'><i class='fas fa-info-circle'></i></a>
                            </h6>
                            <ul class="list-group" id="permissionList">
                                <li class="list-group-item">
                                    <span class="text-success"><i class="fas fa-check-circle"></i></span>
                                    Private use
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                                <li class="list-group-item">
                                    <span class="text-success"><i class="fas fa-check-circle"></i></span>
                                    Distribution
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                                <li class="list-group-item">
                                    <span class="text-success"><i class="fas fa-check-circle"></i></span>
                                    Modification
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h6>Obligations
                                <a href='#' class='text-secondary' data-toggle='modal' data-target='#obligationModal'><i class='fas fa-info-circle'></i></a>
                            </h6>
                            <ul class="list-group" id="obligationList">
                                <li class="list-group-item">
                                <span class="text-info">
                                    <i class="fas fa-exclamation-circle"></i></span>
                                    Attribution
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                                <li class="list-group-item"><span class="text-info">
                                    <i class="fas fa-exclamation-circle"></i></span>
                                    Liability
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h6>Prohibitions
                                <a href='#' class='text-secondary' data-toggle='modal' data-target='#prohibitionModal'><i class='fas fa-info-circle'></i></a>
                            </h6>
                            <ul class="list-group" id="prohibitionList">
                                <li class="list-group-item">
                                    <span class="text-danger"><i class="fas fa-times-circle"></i></span>
                                    Commercial use
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                                <li class="list-group-item">
                                    <span class="text-danger"><i class="fas fa-times-circle"></i></span>
                                    Modification
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#viewModal">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- *** [END] MODAL - LICENSE VIEW *** -->


    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>

            <h2>Licenses and policies</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->
            <br /><br />

            <?php
            $activeTab = [
                'index' => false,
                'requests' => true,
                'dataset' => $dataset,
                'agent' => 'user'
            ];
            if ($can_edit) {
                $activeTab['agent'] == 'manager';
            }
            ?>
            <?= $this->partial('mkdf/policies/partial/navtabs', $activeTab); ?>

            <br />

            <div class="row">
                <div class="col-md-12">
                    <h4>License requests</h4>

                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>

                            <th scope="col">Created</th>
                            <th scope="col">Last modified</th>
                            <?php if($can_edit): ?>
                                <th scope="col">User</th>
                            <?php endif; ?>
                            <th scope="col">Request history</th>
                            <th scope="col">Status</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($requests as $request): ?>
                        <tr>
                            <th scope="row"><?= date('Y/m/d H:i',$request['createdAt']) ?></th>
                            <td><?= date('Y/m/d H:i',$request['modifiedAt']) ?></td>
                            <?php if($can_edit): ?>
                                <td><?= $request['user'] ?></td>
                            <?php endif; ?>
                            <td>
                                <div class="accordion" id="accordionExample">




                                <?php foreach($request['history'] as $historyItem): ?>
                                    <div class="card">
                                        <div class="card-header" id="<?= ('heading-'.$historyItem['timestamp']) ?>">
                                            <h5 class="mb-0">
                                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#<?= ('collapse-'.$historyItem['timestamp']) ?>" aria-expanded="true" aria-controls="<?= ('collapse-'.$historyItem['timestamp']) ?>">
                                                    <?= $historyItem['type'] ?>
                                                </button>
                                            </h5>
                                        </div>

                                        <div id="<?= ('collapse-'.$historyItem['timestamp']) ?>" class="collapse" aria-labelledby="<?= ('heading-'.$historyItem['timestamp']) ?>" data-parent="#accordionExample">
                                            <div class="card-body">

                                                <em><?= date('Y/m/d H:i',$historyItem['timestamp']) ?></em><br />
                                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#historyItemModal" onclick="loadHistoryItem('<?= htmlspecialchars(json_encode($historyItem)) ?>')">
                                                    <i class="fas fa-search"></i> View
                                                </button>
                                                <!--<?= $historyItem['title'] ?><br />-->
                                                <!--<?= $historyItem['description'] ?><br />-->
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                                </div>

                            </td>

                            <?php
                            switch ($request['status']) {
                                case 'APPROVED':
                                    $statusClass = 'bg-success';
                                    break;
                                case 'REQUEST':
                                    $statusClass = 'bg-warning';
                                    break;
                                case 'REJECTED':
                                    $statusClass = 'bg-danger';
                                    break;
                                case 'COUNTER OFFER':
                                    $statusClass = 'bg-warning';
                                    break;
                                case 'COUNTER REQUEST':
                                    $statusClass = 'bg-warning';
                                    break;

                                default:
                                    $statusClass = 'bg-warning';
                            }
                            ?>

                            <td class="<?= $statusClass ?>"><?= $request['status'] ?></td>
                            <td>
                                <!--<div class="btn-group" role="group" aria-label="Basic example">-->
                                    <!-- <a class="btn btn-warning" href="#" role="button"><i class="fas fa-edit"></i> Modify license</a> -->

                                <?php
                                    // Determine appropriate actions here based on current status and also whether user/manager.
                                    if ($can_edit){ // Dataset Manager
                                        switch ($request['status']) {
                                            case 'REQUEST':
                                                // approve, reject, counter offer
                                                $button = '<a class="btn btn-primary" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'approve'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-thumbs-up"></i> Approve</a>';
                                                print($button.'<br />');
                                                $button = '<a class="btn btn-danger" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'reject'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-thumbs-down"></i> Reject</a>';
                                                print($button.'<br />');
                                                $button = '<a class="btn btn-warning" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'counter'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-reply"></i> Counter offer</a>';
                                                print($button);
                                                break;
                                            case 'COUNTER REQUEST':
                                                // approve, reject, counter offer
                                                $button = '<a class="btn btn-primary" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'approve'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-thumbs-up"></i> Approve</a>';
                                                print($button.'<br />');
                                                $button = '<a class="btn btn-danger" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'reject'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-thumbs-down"></i> Reject</a>';
                                                print($button.'<br />');
                                                $button = '<a class="btn btn-warning" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'counter'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-reply"></i> Counter offer</a>';
                                                print($button);
                                                break;
                                            default:
                                                //No actions
                                        }
                                    }
                                    else { // Dataset User
                                        switch ($request['status']) {
                                            case 'COUNTER OFFER':
                                                // aaccept, reject, counter request
                                                $button = '<a class="btn btn-primary" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'approve'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-thumbs-up"></i> Accept</a>';
                                                print($button.'<br />');
                                                $button = '<a class="btn btn-danger" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'reject'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-thumbs-down"></i> Reject</a>';
                                                print($button.'<br />');
                                                $button = '<a class="btn btn-warning" href="'.$this->url( 'dataset-policies', ['id'=>$dataset->id, 'action'=>'counter'],['query' => ['request' => $request['_id']]]).'" role="button"><i class="fas fa-reply"></i> Counter request</a>';
                                                print($button);
                                                break;
                                            default:
                                                //No actions
                                        }
                                    }
                                ?>
                                <!--</div>-->
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    function loadHistoryItem(JSONInput) {
        historyItem = JSON.parse(JSONInput);
        $("#permissionList").empty();
        $("#obligationList").empty();
        $("#prohibitionList").empty();

        const showPoliciesTypes = ["REQUEST", "COUNTER OFFER", "COUNTER REQUEST"];
        if (showPoliciesTypes.includes(historyItem['type'])) {
            $("#policiesRow").show();
            renderPermissions(historyItem['policies']['permissions']);
            renderObligations(historyItem['policies']['obligations']);
            renderProhibitions(historyItem['policies']['prohibitions']);
        }
        else {
            $("#policiesRow").hide();
        }
        var newDate = new Date();
        newDate.setTime(historyItem['timestamp']*1000);
        dateString = newDate.toUTCString();

        historyHTML = "<strong>Action : </strong>" + historyItem['type'] + "<br />";
        historyHTML += "<strong>Date: </strong>" + dateString + "<br />";

        switch(historyItem['type']) {
            case 'REQUEST':
                historyHTML += "<strong>Request title: </strong>" + historyItem['title'] + "<br />";
                historyHTML += "<strong>Request description: </strong>" + historyItem['description'] + "<br />";
                historyHTML += "<hr />";
                break;
            case 'APPROVE':
                historyHTML += "<strong>New license title: </strong>" + historyItem['title'] + "<br />";
                historyHTML += "<strong>Description and notes: </strong>" + historyItem['description'] + "<br />";
                historyHTML += "<em>This license is now available to select when registering API keys on this dataset.</em>"
                break;
            case 'REJECT':
                historyHTML += "<strong>Rejection reason: </strong>" + historyItem['title'] + "<br />";
                historyHTML += "<strong>Description and notes: </strong>" + historyItem['description'] + "<br />";
                break;
            case 'COUNTER OFFER':
                historyHTML += "<strong>License title: </strong>" + historyItem['title'] + "<br />";
                historyHTML += "<strong>Description and notes: </strong>" + historyItem['description'] + "<br />";
                historyHTML += "<hr />";
                break;
            case 'COUNTER REQUEST':
                historyHTML += "<strong>Request title: </strong>" + historyItem['title'] + "<br />";
                historyHTML += "<strong>Request description: </strong>" + historyItem['description'] + "<br />";
                historyHTML += "<hr />";
                break;
            default:
            // code block
        }

        $("#historyItemModalContent").html(historyHTML);
        //console.log(historyItem);
    }

    function renderPermissions(permissions) {
        //console.log(permissions);
        $("#permissionList").empty();
        if (Array.isArray(permissions)) {
            modalText = '';
            for (i = 0; i < permissions.length; i++) {
                liText = "<li class='list-group-item'> <span class='text-success'> <i class='fas fa-check-circle'></i></span>";
                liText += " " + getShortName(permissions[i].action[0]) + " ";
                if (i > 0) {
                    modalText += "<hr />";
                }
                modalText += "<h6>" + permissions[i].action[0] + "</h6>";
                modalText += "<p><em>permission description</em></p>";

                if (Array.isArray(permissions[i].duty)) {
                    liText += "<a href='#' class='text-warning' data-toggle='tooltip' data-placement='top' title='One or more duties are attached to this permission policy'>";
                    liText += "<i class='fas fa-exclamation-circle'></i></a>";
                    modalText += "<p> <span class='text-danger'><i class='fas fa-exclamation-circle'></i></span> The following duties are attached to this permission:<br />";
                    for (j = 0; j < permissions[i].duty.length; j++) {
                        modalText += "<em>" + permissions[i].duty[j] + "</em><br />";
                    }
                    modalText += "</p>";

                }
                $("#permissionList").append(liText);
                //$("#permissionModalContent").html(modalText);
            }
        }
    }

    function renderObligations(obligations) {
        $("#obligationList").empty();
        if (Array.isArray(obligations)) {
            modalText = '';
            for (i = 0; i < obligations.length; i++) {
                liText = "<li class='list-group-item'> <span class='text-info'> <i class='fas fa-exclamation-circle'></i></span>";
                liText += " " + getShortName(obligations[i].action[0]) + " ";
                if (i > 0) {
                    modalText += "<hr />";
                }
                modalText += "<h6>" + obligations[i].action[0] + "</h6>";
                modalText += "<p><em>obligation description</em></p>";
                $("#obligationList").append(liText);
                //$("#obligationModalContent").html(modalText);

            }
        }
    }

    function renderProhibitions(prohibitions) {
        $("#prohibitionList").empty();
        if (Array.isArray(prohibitions)) {
            modalText = '';
            for (i = 0; i < prohibitions.length; i++) {
                liText = "<li class='list-group-item'> <span class='text-danger'> <i class='fas fa-times-circle'></i></span>";
                liText += " " + getShortName(prohibitions[i].action[0]) + " ";
                if (i > 0) {
                    modalText += "<hr />";
                }
                modalText += "<h6>" + prohibitions[i].action[0] + "</h6>";
                modalText += "<p><em>prohibition description</em></p>";
                $("#prohibitionList").append(liText);
                //$("#prohibitionModalContent").html(modalText);
            }
        }
    }

    function getShortName(input) {
        position = input.lastIndexOf('#');
        if (position < 0){
            position = input.lastIndexOf(':');
        }
        if (position < 0) {
            return input;
        }
        else {
            return input.substring(position + 1);
        }
    }
</script>